name: wifi
description: Flutter plugin providing WiFi.
homepage: https://github.com/once10301/wifi
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.ly.wifi
        pluginClass: WifiPlugin

dependencies:
  flutter:
    sdk: flutter